### ISSUE TITLE
自建服务端

### ISSUE THREAD

**Issue by fcwys** [boywhp/fcn#27]
请问如何自建服务端？希望支持自建公网服务端

**Comment by boywhp** [comment]
企业版支持自己建FCN公网服务器，RMB 5000授权发自我的华为手机-------- 原始邮件 --------主题：[boywhp/fcn] 自建服务端 (#27)发件人：fcwys 收件人：boywhp/fcn 抄送：Subscribed 请问如何自建服务端？希望支持自建公网服务端



—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/boywhp/fcn","title":"boywhp/fcn","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/boywhp/fcn"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"自建服务端 (#27)"}],"action":{"name":"View Issue","url":"https://github.com/boywhp/fcn/issues/27"}}}

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/boywhp/fcn/issues/27",

"url": "https://github.com/boywhp/fcn/issues/27",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]
